# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, null=True)),
                ('ipaddress', models.CharField(max_length=32, null=True)),
                ('system', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
