# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True)),
                ('password', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
