# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20190113_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='region',
            field=models.CharField(max_length=32, null=True, verbose_name='机房'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
