# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_auto_20190117_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlist',
            name='host_region_computer_room_id',
            field=models.CharField(max_length=32, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='区域'),
        ),
    ]
