# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0009_auto_20190117_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='computer_room',
            field=models.ManyToManyField(null=True, to='host.ComputerRoom', verbose_name='机房'),
        ),
    ]
