# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_region_computer_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostlist',
            name='computer_room',
        ),
        migrations.AddField(
            model_name='computerroom',
            name='hosts',
            field=models.ManyToManyField(null=True, to='host.HostList', verbose_name='本机房所属 主机'),
        ),
    ]
