# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0014_auto_20190130_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='密码'),
        ),
    ]
