# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0016_auto_20190207_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '一级菜单', 'verbose_name_plural': '一级菜单'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '岗位', 'verbose_name_plural': '岗位'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
